overrides:
  ceph:
    log-whitelist:
    - reached quota
    - wrongly marked me down
    - overall HEALTH_
    - (POOL_FULL)
    - (SMALLER_PGP_NUM)
    - (CACHE_POOL_NO_HIT_SET)
    - (CACHE_POOL_NEAR_FULL)
tasks:
- workunit:
    clients:
      client.0:
        - rados/test.sh
        - rados/test_pool_quota.sh

