
overrides:
  ceph:
    log-whitelist:
      - responding to mclientcaps\(revoke\)
      - not advance its oldest_client_tid

tasks:
  - cephfs_test_runner:
      fail_on_skip: false
      modules:
        - tasks.cephfs.test_client_limits
